#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase
touch $(basename $PWD).foam

rm PyFoam*

if [ -d "Gnuplotting.analyzed" ]; then
    rm -r Gnuplotting.analyzed/
fi

#------------------------------------------------------------------------------
