#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Commands to run in the terminal
blockMesh
surfaceFeatureExtract
snappyHexMesh -overwrite

transformPoints -scale 0.001

pyFoamPlotRunner.py simpleFoam

#------------------------------------------------------------------------------
